services:
  mqtt:
    container_name: mqtt
    image: docker.io/iegomez/mosquitto-go-auth:latest
    # logging:
    #   driver: none
    volumes:
      - ./mqtt/mosquitto.cfg:/etc/mosquitto/mosquitto.conf:ro
    ports:
      - 1883:1883
    restart: unless-stopped

  zigbee_controller:
    depends_on:
      - mqtt
    container_name: zbc
    build: ./zigbee_controller
    ports:
      - 8888:9999
    volumes:
      - ./zigbee_controller:/app
    restart: unless-stopped
    command: uvicorn main:app --log-level info --port 9999 --host "0.0.0.0" --workers 1 --reload
